/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpecialityImport } from './routes/speciality'
import { Route as EnrolleeprofileImport } from './routes/enrolleeprofile'
import { Route as EnrolleeImport } from './routes/enrollee'
import { Route as EmployeeImport } from './routes/employee'
import { Route as ApplicationImport } from './routes/application'
import { Route as AdmissionListImport } from './routes/admissionList'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SpecialityRoute = SpecialityImport.update({
  id: '/speciality',
  path: '/speciality',
  getParentRoute: () => rootRoute,
} as any)

const EnrolleeprofileRoute = EnrolleeprofileImport.update({
  id: '/enrolleeprofile',
  path: '/enrolleeprofile',
  getParentRoute: () => rootRoute,
} as any)

const EnrolleeRoute = EnrolleeImport.update({
  id: '/enrollee',
  path: '/enrollee',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeRoute = EmployeeImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRoute,
} as any)

const ApplicationRoute = ApplicationImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRoute,
} as any)

const AdmissionListRoute = AdmissionListImport.update({
  id: '/admissionList',
  path: '/admissionList',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admissionList': {
      id: '/admissionList'
      path: '/admissionList'
      fullPath: '/admissionList'
      preLoaderRoute: typeof AdmissionListImport
      parentRoute: typeof rootRoute
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationImport
      parentRoute: typeof rootRoute
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeImport
      parentRoute: typeof rootRoute
    }
    '/enrollee': {
      id: '/enrollee'
      path: '/enrollee'
      fullPath: '/enrollee'
      preLoaderRoute: typeof EnrolleeImport
      parentRoute: typeof rootRoute
    }
    '/enrolleeprofile': {
      id: '/enrolleeprofile'
      path: '/enrolleeprofile'
      fullPath: '/enrolleeprofile'
      preLoaderRoute: typeof EnrolleeprofileImport
      parentRoute: typeof rootRoute
    }
    '/speciality': {
      id: '/speciality'
      path: '/speciality'
      fullPath: '/speciality'
      preLoaderRoute: typeof SpecialityImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissionList': typeof AdmissionListRoute
  '/application': typeof ApplicationRoute
  '/employee': typeof EmployeeRoute
  '/enrollee': typeof EnrolleeRoute
  '/enrolleeprofile': typeof EnrolleeprofileRoute
  '/speciality': typeof SpecialityRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissionList': typeof AdmissionListRoute
  '/application': typeof ApplicationRoute
  '/employee': typeof EmployeeRoute
  '/enrollee': typeof EnrolleeRoute
  '/enrolleeprofile': typeof EnrolleeprofileRoute
  '/speciality': typeof SpecialityRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admissionList': typeof AdmissionListRoute
  '/application': typeof ApplicationRoute
  '/employee': typeof EmployeeRoute
  '/enrollee': typeof EnrolleeRoute
  '/enrolleeprofile': typeof EnrolleeprofileRoute
  '/speciality': typeof SpecialityRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissionList'
    | '/application'
    | '/employee'
    | '/enrollee'
    | '/enrolleeprofile'
    | '/speciality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissionList'
    | '/application'
    | '/employee'
    | '/enrollee'
    | '/enrolleeprofile'
    | '/speciality'
  id:
    | '__root__'
    | '/'
    | '/admissionList'
    | '/application'
    | '/employee'
    | '/enrollee'
    | '/enrolleeprofile'
    | '/speciality'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionListRoute: typeof AdmissionListRoute
  ApplicationRoute: typeof ApplicationRoute
  EmployeeRoute: typeof EmployeeRoute
  EnrolleeRoute: typeof EnrolleeRoute
  EnrolleeprofileRoute: typeof EnrolleeprofileRoute
  SpecialityRoute: typeof SpecialityRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionListRoute: AdmissionListRoute,
  ApplicationRoute: ApplicationRoute,
  EmployeeRoute: EmployeeRoute,
  EnrolleeRoute: EnrolleeRoute,
  EnrolleeprofileRoute: EnrolleeprofileRoute,
  SpecialityRoute: SpecialityRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/admissionList",
        "/application",
        "/employee",
        "/enrollee",
        "/enrolleeprofile",
        "/speciality"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/admissionList": {
      "filePath": "admissionList.jsx"
    },
    "/application": {
      "filePath": "application.jsx"
    },
    "/employee": {
      "filePath": "employee.jsx"
    },
    "/enrollee": {
      "filePath": "enrollee.jsx"
    },
    "/enrolleeprofile": {
      "filePath": "enrolleeprofile.jsx"
    },
    "/speciality": {
      "filePath": "speciality.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
